
INSERT INTO videos (url, language, duration_s, status) VALUES ('https://www.youtube.com/watch?v=LDSUPQNbueE', 'en', 1026, 'ingested');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 0.000, 2.939, 'and what''s going on everyone it''s');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1.319, 4.080, 'stranger and welcome back to another');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 2.939, 6.210, 'video');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 4.080, 8.610, 'and it''s been a while since I did an');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 6.210, 10.530, 'aiming tutorial so I thought I''d bring');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 8.610, 13.139, 'it all up to date and do a new');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 10.530, 15.780, 'walkthrough on how I edit and create');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 13.139, 22.859, 'Amon breaks so we''ll just get right into');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 15.780, 26.640, 'it I have here an Amon break here it''s a');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 22.859, 29.760, 'pretty raw unedited file ripped straight');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 26.640, 32.940, 'from the record I''ll include a link to');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 29.760, 35.579, 'it in the comments below and I pulled it');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 32.940, 38.010, 'it as an audio here so I''m just gonna');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 35.579, 43.469, 'let me just play it I''ll just play at a');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 38.010, 45.840, 'slower tempo since Ableton will re well');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 43.469, 49.110, 'sequence it to the right BPM of your');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 45.840, 57.960, 'track so just play it slower so we can');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 49.110, 58.920, 'hear how it sounds that''s sounding');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 57.960, 103.180, 'pretty tough');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 58.920, 106.600, 'this is sounding pretty crisp and the');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 103.180, 109.240, 'section I liked using what the Amon is U');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 106.600, 114.400, 'is mostly this section here is the last');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 109.240, 118.750, 'bar and a half so typically I would cut');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 114.400, 122.020, 'every slice of the entire sample but');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 118.750, 124.090, 'just to make things a bit quicker today');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 122.020, 126.210, 'I''m just going to cut the section that I');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 124.090, 130.210, 'use most or just this section over here');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 126.210, 133.150, 'so I''m just gonna first mark the');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 130.210, 137.170, 'beginning where I want to cut I''m just');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 133.150, 140.200, 'here and then what I''m gonna do is I''m');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 137.170, 143.890, 'just gonna highlight this section right');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 140.200, 146.950, 'click select loop selection and then');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 143.890, 150.360, 'right click again and select crop so');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 146.950, 154.149, 'what crop does is it cuts the sample');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 150.360, 157.780, 'between the your loop points so that''s');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 154.149, 200.030, 'why we loop first we select your the');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 157.780, 203.329, 'sample loop it and then crop it now you');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 200.030, 209.110, 'have a condensed sample and we can get');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 203.329, 209.110, 'rid of this as well');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 209.650, 216.410, 'you just do that again crop sample');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 213.500, 220.400, 'perfect and now we can actually cut the');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 216.410, 224.150, 'slices so but diesel Abelson has');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 220.400, 228.520, 'identified the transience whereas which');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 224.150, 233.810, 'is where that there are percussive hits');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 228.520, 236.000, 'there''s like a defined hit at these');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 233.810, 239.480, 'points and you can kind of tell there''s');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 236.000, 242.840, 'this little triangle I call it here up');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 239.480, 246.800, 'in the ruler that identifies that there');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 242.840, 250.130, 'is a transient here sometimes I I don''t');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 246.800, 252.230, 'I don''t I don''t trust the algorithm 100%');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 250.130, 256.070, 'so I like the zoom right and just to');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 252.230, 258.470, 'make sure it''s pretty close I mean it''s');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 256.070, 300.510, 'here I personally I would like to cut it');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 258.470, 303.390, 'closer to here so I will just double');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 300.510, 305.790, 'click there but if you like this piece');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 303.390, 308.310, 'then highlight over it and then double');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 305.790, 311.160, 'click what you want is to create a warp');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 308.310, 316.080, 'markers we''re just identified by the');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 311.160, 318.590, 'yellow icon okay and we''ll zoom right in');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 316.080, 323.160, 'so this one is incorrect it has the');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 318.590, 328.360, 'marked or here but this the scenario');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 323.160, 332.030, 'here and as she starts here so if I play');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 328.360, 338.040, '[Music]');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 332.030, 340.739, 'okay and I''ll go into the next hit so');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 338.040, 342.660, 'again it''s not that it''s not perfect it');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 340.739, 347.510, 'has it here I like it probably around');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 342.660, 347.510, 'here zoom right in');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 352.130, 403.889, '[Music]');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 354.579, 405.389, 'now I gotta bring this back to 170 okay');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 403.889, 408.239, 'the next step is we''re gonna right-click');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 405.389, 410.459, 'a where the wave form and select slice');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 408.239, 413.670, 'to MIDI and what this will do is it''ll');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 410.459, 416.400, 'send each slice here to a different pad');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 413.670, 418.739, 'on your drum rack so we''re gonna slice');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 416.400, 421.440, 'the MIDI this window pops up that says');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 418.739, 422.880, 'create one slice pearl warp marker');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 421.440, 428.780, 'that''s correct');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 422.880, 431.340, 'slicing preset this should be fine');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 428.780, 436.590, 'preserve work timing we''re gonna say off');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 431.340, 439.050, 'and we''re gonna click OK okay now I''ve');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 436.590, 441.090, 'just muted my audio channel and now');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 439.050, 444.509, 'we''re gonna listen to the MIDI the drum');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 441.090, 452.789, 'rack as you notice we now have a slice');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 444.509, 455.669, 'for each hit here as you can see it''s a');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 452.789, 500.680, 'now sent the audio to MIDI track here');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 455.669, 503.740, 'okay now I''m just gonna I''m gonna make a');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 500.680, 511.150, 'copy I''m gonna duplicate this MIDI clip');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 503.740, 513.190, 'hit play and then I''m gonna make my own');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 511.150, 519.009, 'pattern so I''m gonna make this two bars');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 513.190, 521.650, 'and get rid of these guys here typically');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 519.009, 525.220, 'what I like to do is I like to quantize');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 521.650, 530.550, 'the eighth notes so that''s any of any');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 525.220, 530.550, 'hits that land on these positions here');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 532.320, 539.320, 'I''ll just do the main hits first hit');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 535.780, 542.199, 'control U and then for these guys to');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 539.320, 544.210, 'preserve the the ghost notes the the');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 542.199, 546.810, 'humanization of the ghost notes');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 544.210, 550.630, 'notice how this ghost note is bit off I');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 546.810, 553.320, 'select small cities and then I move move');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 550.630, 557.409, 'them accordingly so that they''re still');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 553.320, 559.719, 'proportionately in this or relatively in');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 557.409, 602.840, 'the same position however you can just');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 559.719, 605.030, 'move this guy that''s totally fine to how');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 602.840, 608.840, 'violence sometimes I like to collect');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 605.030, 611.479, 'both of these guys and just do that that');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 608.840, 623.720, 'just makes sure my high hats are lined');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 611.479, 626.000, 'up just like from that okay I just want');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 623.720, 632.870, 'to make sure the ends meet');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 626.000, 635.180, 'okay okay pretty good now we can try');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 632.870, 649.760, 'more new-school pattern we can do that');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 635.180, 652.270, 'had a double kick this is a common');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 649.760, 701.340, 'pattern that we use in drum and bass');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 652.270, 704.760, 'especially jungle okay I''m gonna add an');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 701.340, 710.760, 'EQ audio effects bring out eq8');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 704.760, 715.039, 'I like to make my high ends really crisp');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 710.760, 719.310, 'for that new school sound so around');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 715.039, 722.720, 'around 10,000 to 11,000 Hertz will give');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 719.310, 722.720, 'you that new school crisp');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 738.840, 746.440, 'okay that sounded pretty crisp and then');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 743.170, 752.290, 'you can bring up the snares by adjusting');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 746.440, 757.300, 'another EQ I find anywhere between 1200');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 752.290, 802.310, 'Hertz all the way up to around 2800');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 757.300, 810.800, 'Hertz brings out certain aspects of this');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 802.310, 819.040, 'snare it makes a snappier brings up that');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 810.800, 822.700, 'snap sometimes I narrow the resonance to');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 819.040, 825.769, 'to really focus in on that frequency');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 822.700, 825.769, '[Music]');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 828.560, 831.790, '[Music]');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 837.710, 851.340, 'turn it off and on just to see the');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 840.870, 859.470, 'difference okay and to make that''s in');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 851.340, 907.300, 'there pop it''s around 900 Hertz run to');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 859.470, 910.240, '1100 you see how it has that hollow');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 907.300, 927.160, 'sound that makes the snare pop so that''s');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 910.240, 936.430, 'we run 918 for me okay we''ll add another');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 927.160, 938.650, 'YouTube so sometimes what we would like');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 936.430, 941.290, 'to do is send out some of the low mids');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 938.650, 943.750, 'around a 300 area there''s there kind of');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 941.290, 949.390, 'the Box frequencies makes you feel like');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 943.750, 951.690, 'you''re inside a box badass like this');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 949.390, 951.690, 'there');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 959.750, 1004.440, 'another thing you can do is you get');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1001.980, 1007.260, 'pitch to a min now if you pitch it this');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1004.440, 1011.490, 'one it will change all the EQ settings');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1007.260, 1013.530, 'so wait I''m just going to show you you');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1011.490, 1017.250, 'might want to adjust the pitch right');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1013.530, 1020.730, 'away so we can adjust transpose perhaps');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1017.250, 1023.250, 'three semitones up and then you got');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1020.730, 1025.800, 'right click and copy value to siblings');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1023.250, 1031.890, 'because otherwise it''s only to slice');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1025.800, 1033.780, 'that''s pitch it up you notice how it''s');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1031.890, 1047.490, 'just the first hit so right click that');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1033.780, 1051.210, 'transpose pitch copy to siblings so');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1047.490, 1052.650, 'that''s what three semitones up or you');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1051.210, 1102.640, 'can bring it down let''s try three');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1052.650, 1106.390, 'semitones down that''s cool too I''m');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1102.640, 1109.170, 'liking zero at zero pitch though so');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1106.390, 1109.170, 'we''ll just keep it there');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1117.290, 1132.510, 'get out additional hits a second shoe');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1120.420, 1140.970, 'eight the kicks so go find a kick bring');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1132.510, 1146.190, 'that guy in so it''s a double kick to bar');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1140.970, 1147.750, 'Luke so since we have a kick here we can');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1146.190, 1209.020, 'remove some of the lowland from the');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1147.750, 1211.270, 'Aymond adjust the level another way to');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1209.020, 1215.230, 'really give the a man character is to');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1211.270, 1217.930, 'use multiband compression so you guys');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1215.230, 1220.900, 'seen me use this a lot the vase there');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1217.930, 1223.960, 'I''ll pull this guy over here we''ll just');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1220.900, 1227.940, 'turn to EQ off for now and we''ll go');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1223.960, 1227.940, 'through some settings on device there');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1228.690, 1233.039, '[Music]');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1233.760, 1308.570, 'notice how it totally changes its');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1236.080, 1311.240, 'character this one sounded tough now you');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1308.570, 1320.720, 'can try bringing the EQ after and we''ll');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1311.240, 1328.460, 'see how that changes it up yeah I''m');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1320.720, 1331.029, 'liking it before so this is the dry and');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1328.460, 1337.630, 'wet you can adjust the amount of');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1331.029, 1337.630, 'distortion so this is no no Distortion');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1339.250, 1351.500, 'so we''re around here is nice you get a');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1341.870, 1408.540, 'bit up the original signal dam inside');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1351.500, 1412.160, 'and nice and fresh well out a baseline');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1408.540, 1413.660, 'just to hear how that sounds in context');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1412.160, 1416.640, '[Music]');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1413.660, 1419.870, 'yeah it sounds kind of cool so I''m gonna');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1416.640, 1419.870, 'bring in sampler');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1424.780, 1455.330, '[Music]');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1456.350, 1503.270, 'a two bar loop');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1503.630, 1507.169, '[Music]');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1509.400, 1518.090, '[Music]');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1523.930, 1540.929, '[Music]');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1542.930, 1546.620, '[Music]');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1557.040, 1607.919, 'don''t throw 808');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1559.230, 1607.919, '[Music]');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1611.459, 1617.310, 'so there you have it you got some steps');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1614.470, 1620.110, 'to create some fresh sounding amens');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1617.310, 1621.910, 'showed you guys how to eq to a min and');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1620.110, 1624.490, 'then perhaps add some multi-band');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1621.910, 1626.649, 'compression you can definitely take it a');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1624.490, 1629.410, 'step further but I think we''re gonna');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1626.649, 1633.550, 'stop here today and I''ll have a part two');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1629.410, 1636.269, 'on editing and processing your Ament but');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1633.550, 1638.740, 'why don''t you guys focus on this first');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1636.269, 1642.819, 'chopping up the Amen getting a nice');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1638.740, 1645.670, 'little pattern and then e cueing it your');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1642.819, 1648.910, 'cueing itself will take time to master');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1645.670, 1650.290, 'and adding some distortion and then once');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1648.910, 1652.470, 'you have a nice loop then you can add a');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1650.290, 1655.629, 'bassline you and voila');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1652.470, 1658.300, 'so let me know if you found this video');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1655.629, 1700.639, 'helpful like and subscribe if you are');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1658.300, 1703.430, 'into it and let me know what else you''d');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1700.639, 1707.530, 'like to learn in future videos and until');
INSERT INTO video_segments (video_id, start_s, end_s, transcript_fragment) VALUES (1, 1703.430, 1707.530, 'then we''ll see you at the next video');
